services:
  nats:
    image: minideb-nats:1.0
    container_name: nats-server
    ports:
      - "4222:4222"
    command: [
      "/nats-server",
      "-js",
      "-m", "8222"
    ]

  nats-exporter:
    image: natsio/prometheus-nats-exporter:0.17.2
    container_name: nats-exporter
    command: ["-varz", "-jsz=all", "http://nats-server:8222"]
    depends_on: nats

  prometheus:
    image: prom/prometheus:v3.3.0
    container_name: prometheus
    volumes:
      - ./nats-prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - nats-exporter

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
        - ./provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus