volumes:
  nats-data-1:
  nats-data-2:
  nats-data-3:

services:
  nats-1:
    image: minideb-nats:1.0
    container_name: nats-server-1
    volumes:
      - nats-data-1:/tmp/nats
    ports:
      - "4222:4222"
    command: [
      "/nats-server",
      "-js",
      "--server_name", "nats-server-1",
      "--cluster_name", "nats-cluster",
      "--cluster", "nats://0.0.0.0:6222",
      "--routes", "nats://nats-server-2:6222,nats://nats-server-3:6222"
    ]

  nats-2:
    image: minideb-nats:1.0
    container_name: nats-server-2
    volumes:
      - nats-data-2:/tmp/nats
    ports:
      - "4223:4222"
    command: [
      "/nats-server",
      "-js",
      "--server_name", "nats-server-2",
      "--cluster_name", "nats-cluster",
      "--cluster", "nats://0.0.0.0:6222",
      "--routes", "nats://nats-server-1:6222,nats://nats-server-3:6222"
    ]

  nats-3:
    image: minideb-nats:1.0
    container_name: nats-server-3
    volumes:
      - nats-data-3:/tmp/nats
    ports:
      - "4224:4222"
    command: [
      "/nats-server",
      "-js",
      "--server_name", "nats-server-3",
      "--cluster_name", "nats-cluster",
      "--cluster", "nats://0.0.0.0:6222",
      "--routes", "nats://nats-server-1:6222,nats://nats-server-2:6222"
    ]